apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-microservice.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "example-microservice.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "example-microservice.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongoSecret.name }}
              key: connectionString
        - name: NODE_ENV
          value: {{ .Values.nodeEnv }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
